#!/bin/bash
# =============================================================================
# NexaLink Server - Automated Setup Script
# Installs and configures the full NexaLink messaging stack on Ubuntu.
#
# Usage:
#   chmod +x setup.sh && sudo ./setup.sh
#
# What it does:
#   1. Installs Docker and Docker Compose (if missing)
#   2. Generates secure secrets
#   3. Templates all config files with your server parameters
#   4. Starts the full server stack
#   5. Creates the first admin user
# =============================================================================

set -euo pipefail

# --- Colors ---
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

log()  { echo -e "${GREEN}[NexaLink]${NC} $1"; }
warn() { echo -e "${YELLOW}[WARNING]${NC} $1"; }
err()  { echo -e "${RED}[ERROR]${NC} $1" >&2; }

# --- Pre-flight checks ---
if [ "$(id -u)" -ne 0 ]; then
    err "This script must be run as root (use sudo)."
    exit 1
fi

if ! grep -qi 'ubuntu\|debian' /etc/os-release 2>/dev/null; then
    warn "This script is designed for Ubuntu/Debian. Proceeding anyway..."
fi

# --- Determine script and project directories ---
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SERVER_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

log "NexaLink server directory: $SERVER_DIR"

# =============================================================================
# Step 1: Collect configuration
# =============================================================================
echo ""
echo -e "${CYAN}========================================${NC}"
echo -e "${CYAN}   NexaLink Server Setup${NC}"
echo -e "${CYAN}========================================${NC}"
echo ""

# Detect public IP
DETECTED_IP=$(curl -4 -s --max-time 5 ifconfig.co 2>/dev/null || hostname -I | awk '{print $1}')

read -rp "Server IP or domain [$DETECTED_IP]: " SERVER_HOST
SERVER_HOST="${SERVER_HOST:-$DETECTED_IP}"

HTTP_PORT="80"

read -rp "Admin username [admin]: " ADMIN_USER
ADMIN_USER="${ADMIN_USER:-admin}"
# Sanitize: only allow a-z, 0-9, underscore, dash, dot
ADMIN_USER=$(echo "$ADMIN_USER" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9_.-]//g')
if [ -z "$ADMIN_USER" ]; then
    ADMIN_USER="admin"
fi
log "Admin username: $ADMIN_USER"

while true; do
    read -rsp "Admin password (min 8 chars): " ADMIN_PASSWORD
    echo ""
    if [ "${#ADMIN_PASSWORD}" -ge 8 ]; then
        break
    fi
    warn "Password must be at least 8 characters."
done

# Registration always enabled -- users need to be able to sign up
ENABLE_REGISTRATION="true"

# =============================================================================
# Step 2: Install Docker (if needed)
# =============================================================================
install_docker() {
    if command -v docker &>/dev/null; then
        log "Docker already installed: $(docker --version)"
        return
    fi

    log "Installing Docker..."
    apt-get update -qq
    apt-get install -y -qq ca-certificates curl gnupg lsb-release

    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | \
        gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg

    echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
      https://download.docker.com/linux/ubuntu \
      $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
      tee /etc/apt/sources.list.d/docker.list > /dev/null

    apt-get update -qq
    apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-compose-plugin

    systemctl enable docker
    systemctl start docker
    log "Docker installed successfully."
}

install_docker

# Ensure docker compose works
if ! docker compose version &>/dev/null; then
    err "docker compose not available. Please install Docker Compose v2."
    exit 1
fi

# =============================================================================
# Step 3: Generate secrets
# =============================================================================
gen_secret() { openssl rand -hex 32; }

POSTGRES_PASSWORD="$(gen_secret)"
REGISTRATION_SHARED_SECRET="$(gen_secret)"
MACAROON_SECRET="$(gen_secret)"
FORM_SECRET="$(gen_secret)"
TURN_SECRET="$(gen_secret)"
# Admin token is generated and stored for the cleanup script (relay model)
SYNAPSE_ADMIN_TOKEN="$(gen_secret)"

log "Secrets generated."

# =============================================================================
# Step 4: Write .env file
# =============================================================================
cat > "$SERVER_DIR/.env" <<EOF
# NexaLink Server Configuration (auto-generated by setup.sh)
# Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
#
# RELAY MODEL: messages deleted after 1 day, media after 30 days.

SERVER_HOST=${SERVER_HOST}
HTTP_PORT=${HTTP_PORT}
HTTPS_PORT=443
SYNAPSE_PORT=8008
TURN_PORT=3478
TURN_TLS_PORT=5349
TURN_RELAY_MIN=49152
TURN_RELAY_MAX=49172

SYNAPSE_SERVER_NAME=${SERVER_HOST}
SYNAPSE_REPORT_STATS=no
ENABLE_REGISTRATION=${ENABLE_REGISTRATION}
REGISTRATION_SHARED_SECRET=${REGISTRATION_SHARED_SECRET}

POSTGRES_DB=synapse
POSTGRES_USER=synapse
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

TURN_SECRET=${TURN_SECRET}

# Used by cleanup.sh to purge delivered messages via Admin API
SYNAPSE_ADMIN_TOKEN=${SYNAPSE_ADMIN_TOKEN}

ELEMENT_BRAND=NexaLink

ADMIN_USER=${ADMIN_USER}
ADMIN_PASSWORD=${ADMIN_PASSWORD}
GRAFANA_PASSWORD=nexalink123
EOF

chmod 600 "$SERVER_DIR/.env"
log ".env file written."

# =============================================================================
# Step 5: Template config files (using envsubst for reliability)
# =============================================================================

# Export all variables needed by templates
export SERVER_HOST SERVER_NAME="${SERVER_HOST}"
export POSTGRES_USER="synapse" POSTGRES_PASSWORD POSTGRES_DB="synapse"
export ENABLE_REGISTRATION REGISTRATION_SHARED_SECRET
export MACAROON_SECRET FORM_SECRET TURN_SECRET
export TURN_PORT="3478"

TEMPLATE_VARS='${SERVER_HOST} ${SERVER_NAME} ${POSTGRES_USER} ${POSTGRES_PASSWORD} ${POSTGRES_DB} ${ENABLE_REGISTRATION} ${REGISTRATION_SHARED_SECRET} ${MACAROON_SECRET} ${FORM_SECRET} ${TURN_SECRET} ${TURN_PORT}'

template_file() {
    local file="$1"
    log "Templating: $file"
    local tmp="${file}.tmp"
    envsubst "$TEMPLATE_VARS" < "$file" > "$tmp"
    mv "$tmp" "$file"
}

# Copy originals from git before templating (allows re-running setup.sh)
REPO_DIR="$(cd "$SERVER_DIR/.." && pwd)"
if [ -f "$REPO_DIR/.git/HEAD" ]; then
    log "Restoring config templates from git..."
    git -C "$REPO_DIR" checkout -- server/synapse/homeserver.yaml server/coturn/turnserver.conf server/element/config.json 2>/dev/null || true
fi

template_file "$SERVER_DIR/synapse/homeserver.yaml"
template_file "$SERVER_DIR/coturn/turnserver.conf"
template_file "$SERVER_DIR/element/config.json"

log "All config files templated."

# =============================================================================
# Step 6: Generate TLS certificate (Let's Encrypt via nip.io or self-signed)
# =============================================================================
SSL_DIR="$SERVER_DIR/nginx/ssl"
mkdir -p "$SSL_DIR"
mkdir -p "$SERVER_DIR/nginx/certbot"

# Create nip.io domain from IP (e.g. 72.56.244.207 -> 72-56-244-207.nip.io)
NIP_DOMAIN=$(echo "$SERVER_HOST" | tr '.' '-').nip.io
log "Domain for TLS: $NIP_DOMAIN"

# First generate self-signed cert so nginx can start
log "Generating temporary self-signed certificate..."
openssl req -x509 -nodes -days 1 -newkey rsa:2048 \
    -keyout "$SSL_DIR/nexalink.key" \
    -out "$SSL_DIR/nexalink.crt" \
    -subj "/CN=${NIP_DOMAIN}" 2>/dev/null
chmod 600 "$SSL_DIR/nexalink.key"
chmod 644 "$SSL_DIR/nexalink.crt"

# Write HTTPS nginx config with ACME challenge support
log "Writing HTTPS nginx config..."
cat > "$SERVER_DIR/nginx/conf.d/default.conf" <<NGINXCONF
limit_req_zone \$binary_remote_addr zone=synapse_login:10m rate=5r/s;
limit_req_zone \$binary_remote_addr zone=synapse_register:10m rate=3r/s;

server {
    listen 0.0.0.0:80 default_server;
    server_name _;

    # Let's Encrypt ACME challenge
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location /health { access_log off; return 200 "OK\n"; add_header Content-Type text/plain; }
    location / { return 301 https://\$host\$request_uri; }
}

server {
    listen 0.0.0.0:443 ssl default_server;
    resolver 127.0.0.11 valid=10s ipv6=off;
    resolver_timeout 5s;
    server_name _;

    # Try Let's Encrypt cert first, fall back to self-signed
    ssl_certificate     /etc/nginx/ssl/nexalink.crt;
    ssl_certificate_key /etc/nginx/ssl/nexalink.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers off;
    ssl_session_cache shared:SSL:10m;

    add_header X-Content-Type-Options nosniff always;
    add_header X-Frame-Options SAMEORIGIN always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    client_max_body_size 100m;

    # Gzip compression — reduces traffic by 70%
    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_min_length 256;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml text/javascript image/svg+xml;

    # Static file caching — 7 days for hashed assets
    location /assets/ {
        root /usr/share/nginx/www/nexalink;
        expires 7d;
        add_header Cache-Control "public, immutable";
        access_log off;
    }

    location / {
        root /usr/share/nginx/www/nexalink;
        index index.html;
        try_files \$uri \$uri/ /index.html;
    }

    location /element/ { set \$up_element element:80;
        proxy_pass http://\$up_element/; proxy_set_header Host \$host; proxy_set_header X-Real-IP \$remote_addr; proxy_set_header X-Forwarded-Proto \$scheme; }
    location = /element { return 301 /element/; }

    location /_matrix {
        set \$up_synapse synapse:8008;
        proxy_pass http://\$up_synapse;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 600s;
        proxy_buffering off;
    }

    location /_matrix/media {
        set \$up_synapse synapse:8008;
        proxy_pass http://\$up_synapse;
        proxy_set_header Host \$host; proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_buffering off; proxy_read_timeout 300s; client_max_body_size 50m;
    }

    location /.well-known/matrix/ { set \$up_synapse synapse:8008;
        proxy_pass http://\$up_synapse; proxy_set_header Host \$host; }
    location /_synapse { set \$up_synapse synapse:8008;
        proxy_pass http://\$up_synapse; proxy_set_header Host \$host; proxy_set_header X-Real-IP \$remote_addr; }
    location /admin {
        rewrite ^/admin\$ /admin/ permanent;
        rewrite ^/admin/(.*)\$ /\$1 break;
        proxy_pass http://synapse-admin:8080;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
    }

    location /grafana/ {
        proxy_pass http://grafana:3000/grafana/;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }

    location /prometheus/ {
        proxy_pass http://prometheus:9090/;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
    }

    location /_matrix/client/v3/login {
        limit_req zone=synapse_login burst=10 nodelay;
        set \$up_synapse synapse:8008;
        proxy_pass http://\$up_synapse;
        proxy_set_header Host \$host; proxy_set_header X-Real-IP \$remote_addr; proxy_set_header X-Forwarded-Proto \$scheme;
    }
    location /_matrix/client/v3/register {
        limit_req zone=synapse_register burst=10 nodelay;
        set \$up_synapse synapse:8008;
        proxy_pass http://\$up_synapse;
        proxy_set_header Host \$host; proxy_set_header X-Real-IP \$remote_addr; proxy_set_header X-Forwarded-Proto \$scheme;
    }

    location = /config { set \$up_api admin-api:9090;
        proxy_pass http://\$up_api/; proxy_set_header Host \$host; }
    location /api/ { set \$up_api admin-api:9090;
        proxy_pass http://\$up_api; proxy_set_header Host \$host; }
    location /installers/ {
        alias /usr/share/nginx/www/installers/;
        autoindex off;

        # Force download for all installer files
        add_header Content-Disposition 'attachment' always;
        add_header Cache-Control 'public, max-age=3600' always;
        add_header X-Content-Type-Options 'nosniff' always;

        # Correct MIME types
        types {
            application/x-bat bat;
            application/x-sh sh;
            application/x-executable AppImage;
            application/x-msdownload exe;
            application/vnd.android.package-archive apk;
            text/html html;
        }
        default_type application/octet-stream;

        # Efficient file serving for high concurrency
        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
    }
    location /installers/desktop/ {
        alias /usr/share/nginx/www/nexalink/installers/desktop/;
        autoindex off;
        default_type application/octet-stream;
        types {
            application/x-msdownload exe;
            application/x-executable AppImage;
            application/x-debian-package deb;
            application/octet-stream blockmap;
        }
        add_header Content-Disposition 'attachment' always;
        add_header Cache-Control 'public, max-age=3600' always;
        add_header X-Content-Type-Options 'nosniff' always;
        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
    }
    location /installers/native/ {
        alias /usr/share/nginx/www/installers/native/;
        autoindex off;
        default_type application/octet-stream;
        add_header Content-Disposition 'attachment' always;
        add_header Cache-Control 'public, max-age=3600' always;
        sendfile on;
    }
    location /health { access_log off; return 200 "OK\n"; add_header Content-Type text/plain; }
}
NGINXCONF
log "HTTPS nginx config written."

# =============================================================================
# Step 6b: Create directories for nginx static files
# =============================================================================
mkdir -p "$SERVER_DIR/nginx/www/installers"
mkdir -p "$SERVER_DIR/nginx/www/nexalink"

# Generate platform installers pointing to this server (HTTPS with nip.io)
BASE_URL="https://${NIP_DOMAIN}"
if [ "$HTTP_PORT" != "80" ]; then
    BASE_URL="http://${SERVER_HOST}:${HTTP_PORT}"
fi

# Windows installer
cat > "$SERVER_DIR/nginx/www/installers/NexaLink-Install.bat" <<WINEOF
@echo off
title NexaLink Installer
color 0A
echo.
echo  ========================================
echo     NexaLink - Decentralized Messenger
echo  ========================================
echo.
echo  Installing NexaLink...

set "SERVER_URL=${BASE_URL}"

mkdir "%USERPROFILE%\NexaLink" 2>nul

echo @echo off > "%USERPROFILE%\NexaLink\NexaLink.bat"
echo start "" "%SERVER_URL%" >> "%USERPROFILE%\NexaLink\NexaLink.bat"

echo Set ws = CreateObject("WScript.Shell") > "%TEMP%\ml_sc.vbs"
echo Set sc = ws.CreateShortcut(ws.SpecialFolders("Desktop") ^& "\NexaLink.lnk") >> "%TEMP%\ml_sc.vbs"
echo sc.TargetPath = "%USERPROFILE%\NexaLink\NexaLink.bat" >> "%TEMP%\ml_sc.vbs"
echo sc.IconLocation = "shell32.dll,14" >> "%TEMP%\ml_sc.vbs"
echo sc.Description = "NexaLink Messenger" >> "%TEMP%\ml_sc.vbs"
echo sc.WindowStyle = 7 >> "%TEMP%\ml_sc.vbs"
echo sc.Save >> "%TEMP%\ml_sc.vbs"
cscript //nologo "%TEMP%\ml_sc.vbs"
del "%TEMP%\ml_sc.vbs" 2>nul

mkdir "%APPDATA%\Microsoft\Windows\Start Menu\Programs\NexaLink" 2>nul
echo Set ws = CreateObject("WScript.Shell") > "%TEMP%\ml_sm.vbs"
echo Set sc = ws.CreateShortcut("%APPDATA%\Microsoft\Windows\Start Menu\Programs\NexaLink\NexaLink.lnk") >> "%TEMP%\ml_sm.vbs"
echo sc.TargetPath = "%USERPROFILE%\NexaLink\NexaLink.bat" >> "%TEMP%\ml_sm.vbs"
echo sc.IconLocation = "shell32.dll,14" >> "%TEMP%\ml_sm.vbs"
echo sc.Description = "NexaLink Messenger" >> "%TEMP%\ml_sm.vbs"
echo sc.Save >> "%TEMP%\ml_sm.vbs"
cscript //nologo "%TEMP%\ml_sm.vbs"
del "%TEMP%\ml_sm.vbs" 2>nul

echo.
echo  ========================================
echo   Done! Shortcut created on Desktop.
echo   Opening NexaLink now...
echo  ========================================

start "" "%SERVER_URL%"
exit
WINEOF

# Linux installer
cat > "$SERVER_DIR/nginx/www/installers/nexalink-install.sh" <<LINEOF
#!/bin/bash
# NexaLink Installer for Linux

SERVER_URL="${BASE_URL}"

echo ""
echo "========================================"
echo "   NexaLink - Decentralized Messenger"
echo "========================================"
echo ""
echo "Installing..."

mkdir -p "\$HOME/NexaLink"

cat > "\$HOME/NexaLink/nexalink" << 'LAUNCHER'
#!/bin/bash
xdg-open "${BASE_URL}" 2>/dev/null || sensible-browser "${BASE_URL}" 2>/dev/null || firefox "${BASE_URL}" 2>/dev/null || google-chrome "${BASE_URL}" 2>/dev/null
LAUNCHER
chmod +x "\$HOME/NexaLink/nexalink"

mkdir -p "\$HOME/.local/share/applications"
cat > "\$HOME/.local/share/applications/nexalink.desktop" << DESKTOP
[Desktop Entry]
Version=1.0
Name=NexaLink
Comment=Decentralized Encrypted Messenger
Exec=xdg-open ${BASE_URL}
Icon=internet-chat
Terminal=false
Type=Application
Categories=Network;InstantMessaging;Chat;
DESKTOP

DESKTOP_DIR=\$(xdg-user-dir DESKTOP 2>/dev/null || echo "\$HOME/Desktop")
if [ -d "\$DESKTOP_DIR" ]; then
    cp "\$HOME/.local/share/applications/nexalink.desktop" "\$DESKTOP_DIR/"
    chmod +x "\$DESKTOP_DIR/nexalink.desktop" 2>/dev/null
    gio set "\$DESKTOP_DIR/nexalink.desktop" metadata::trusted true 2>/dev/null
fi

update-desktop-database "\$HOME/.local/share/applications" 2>/dev/null

echo ""
echo "Done! Shortcut created on Desktop."
echo "Opening NexaLink now..."
echo ""

xdg-open "${BASE_URL}" 2>/dev/null || sensible-browser "${BASE_URL}" 2>/dev/null || echo "Open ${BASE_URL} in your browser"
LINEOF
chmod +x "$SERVER_DIR/nginx/www/installers/nexalink-install.sh"

# Android installer page (PWA with auto-install prompt)
cat > "$SERVER_DIR/nginx/www/installers/NexaLink-Android.html" <<ANDROIDEOF
<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Install NexaLink - Android</title>
<link rel="manifest" href="/manifest.json">
<style>body{font-family:system-ui;background:#0a0a12;color:#e0e0e0;display:flex;align-items:center;justify-content:center;min-height:100vh;margin:0;padding:1rem}
.card{max-width:400px;text-align:center;padding:2rem;border-radius:1.5rem;background:rgba(255,255,255,.05);border:1px solid rgba(255,255,255,.1)}
h1{font-size:1.5rem;background:linear-gradient(135deg,#a855f7,#6366f1);-webkit-background-clip:text;-webkit-text-fill-color:transparent}
.step{text-align:left;margin:1rem 0;line-height:1.8;font-size:.9rem;color:#aaa}
.btn{display:inline-block;padding:.8rem 2rem;border-radius:1rem;background:linear-gradient(135deg,#a855f7,#6366f1);color:#fff;text-decoration:none;font-weight:600;margin-top:1rem;border:none;cursor:pointer;font-size:1rem}
.btn:active{transform:scale(.97)}
.hidden{display:none}
.success{color:#22c55e;font-size:1.2rem;margin:1rem 0}</style>
</head><body><div class="card">
<h1>NexaLink for Android</h1>
<div id="auto-install">
<p style="color:#aaa;margin:1rem 0">Tap the button below to install NexaLink on your device:</p>
<button id="install-btn" class="btn" onclick="installApp()">Install NexaLink</button>
<p id="installed-msg" class="success hidden">NexaLink installed! Check your home screen.</p>
</div>
<div id="manual-install" class="hidden">
<div class="step">
<p>1. Open <a href="${BASE_URL}" style="color:#a855f7">${BASE_URL}</a> in Chrome</p>
<p>2. Tap menu <b>&#8942;</b> (top right)</p>
<p>3. Tap <b>"Install app"</b> or <b>"Add to Home screen"</b></p>
<p>4. NexaLink icon appears on your home screen</p>
</div>
</div>
<a href="${BASE_URL}" class="btn" style="margin-top:1.5rem">Open NexaLink</a>
</div>
<script>
let deferredPrompt=null;
window.addEventListener('beforeinstallprompt',function(e){e.preventDefault();deferredPrompt=e;document.getElementById('install-btn').classList.remove('hidden');document.getElementById('manual-install').classList.add('hidden')});
function installApp(){if(deferredPrompt){deferredPrompt.prompt();deferredPrompt.userChoice.then(function(r){if(r.outcome==='accepted'){document.getElementById('install-btn').classList.add('hidden');document.getElementById('installed-msg').classList.remove('hidden')}deferredPrompt=null})}else{document.getElementById('auto-install').classList.add('hidden');document.getElementById('manual-install').classList.remove('hidden')}}
window.addEventListener('appinstalled',function(){document.getElementById('install-btn').classList.add('hidden');document.getElementById('installed-msg').classList.remove('hidden')});
if('serviceWorker' in navigator){navigator.serviceWorker.register('/sw.js').catch(function(){})}
</script>
</body></html>
ANDROIDEOF

# iOS installer page
cat > "$SERVER_DIR/nginx/www/installers/NexaLink-iOS.html" <<IOSEOF
<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Install NexaLink - iOS</title>
<style>body{font-family:system-ui;background:#0a0a12;color:#e0e0e0;display:flex;align-items:center;justify-content:center;min-height:100vh;margin:0;padding:1rem}
.card{max-width:400px;text-align:center;padding:2rem;border-radius:1.5rem;background:rgba(255,255,255,.05);border:1px solid rgba(255,255,255,.1)}
h1{font-size:1.5rem;background:linear-gradient(135deg,#a855f7,#6366f1);-webkit-background-clip:text;-webkit-text-fill-color:transparent}
.step{text-align:left;margin:1rem 0;line-height:1.8;font-size:.9rem;color:#aaa}
.btn{display:inline-block;padding:.8rem 2rem;border-radius:1rem;background:linear-gradient(135deg,#a855f7,#6366f1);color:#fff;text-decoration:none;font-weight:600;margin-top:1rem}</style>
</head><body><div class="card">
<h1>NexaLink for iOS</h1>
<div class="step">
<p>1. Open <a href="${BASE_URL}" style="color:#a855f7">${BASE_URL}</a> in Safari</p>
<p>2. Tap Share <b>↑</b> (bottom bar)</p>
<p>3. Tap <b>"Add to Home Screen"</b></p>
<p>4. NexaLink icon appears on your home screen</p>
</div>
<a href="${BASE_URL}" class="btn">Open NexaLink</a>
</div></body></html>
IOSEOF

log "Platform installers generated."

# =============================================================================
# Step 7: Generate server signing key
# =============================================================================
# CRITICAL: Clean up Docker volume artifacts
# Docker creates DIRECTORIES instead of files when mounting non-existent paths
# This happens after failed installs or docker compose up before files exist
log "Cleaning Docker volume artifacts..."
for f in signing.key homeserver.yaml log.config; do
    if [ -d "$SERVER_DIR/synapse/$f" ]; then
        log "  Removing directory artifact: synapse/$f"
        rm -rf "$SERVER_DIR/synapse/$f"
    fi
done
if [ -d "/data/signing.key" ]; then
    rm -rf "/data/signing.key"
fi
for f in turnserver.conf; do
    if [ -d "$SERVER_DIR/coturn/$f" ]; then
        rm -rf "$SERVER_DIR/coturn/$f"
    fi
done
for f in config.json; do
    if [ -d "$SERVER_DIR/element/$f" ]; then
        rm -rf "$SERVER_DIR/element/$f"
    fi
done

# Stop containers before volume operations
docker compose -f "$SERVER_DIR/docker-compose.yml" down 2>/dev/null || true
docker volume rm server_synapse_data 2>/dev/null || true

# Restore config files if they were deleted by artifact cleanup
if [ ! -f "$SERVER_DIR/synapse/homeserver.yaml" ]; then
    log "Restoring homeserver.yaml..."
    git -C "$REPO_DIR" checkout -- server/synapse/homeserver.yaml 2>/dev/null || true
    template_file "$SERVER_DIR/synapse/homeserver.yaml"
fi
if [ ! -f "$SERVER_DIR/synapse/log.config" ]; then
    log "Restoring log.config..."
    git -C "$REPO_DIR" checkout -- server/synapse/log.config 2>/dev/null || true
fi
if [ ! -f "$SERVER_DIR/coturn/turnserver.conf" ]; then
    log "Restoring turnserver.conf..."
    git -C "$REPO_DIR" checkout -- server/coturn/turnserver.conf 2>/dev/null || true
    template_file "$SERVER_DIR/coturn/turnserver.conf"
fi
if [ ! -f "$SERVER_DIR/element/config.json" ]; then
    log "Restoring config.json..."
    git -C "$REPO_DIR" checkout -- server/element/config.json 2>/dev/null || true
    template_file "$SERVER_DIR/element/config.json"
fi

if [ ! -f "$SERVER_DIR/synapse/signing.key" ]; then
    log "Generating server signing key..."
    docker run --rm \
        -v "$SERVER_DIR/synapse:/data" \
        -e SYNAPSE_SERVER_NAME="$SERVER_HOST" \
        -e SYNAPSE_REPORT_STATS=no \
        --entrypoint python3 \
        matrixdotorg/synapse:latest \
        -m synapse.app.homeserver \
        --config-path /data/homeserver.yaml \
        --generate-keys
    log "Signing key generated."
else
    log "Signing key already exists, skipping generation."
fi

# Verify all required files exist before proceeding
log "Verifying config files..."
MISSING=false
for f in "$SERVER_DIR/synapse/homeserver.yaml" "$SERVER_DIR/synapse/signing.key" "$SERVER_DIR/synapse/log.config" "$SERVER_DIR/coturn/turnserver.conf" "$SERVER_DIR/element/config.json"; do
    if [ ! -f "$f" ]; then
        err "MISSING: $f"
        MISSING=true
    fi
done
if [ "$MISSING" = "true" ]; then
    err "Required config files are missing. Cannot start server."
    exit 1
fi
log "All config files verified."

# Fix permissions: Synapse runs as UID 991 inside the container
log "Fixing file permissions..."
chmod 644 "$SERVER_DIR/synapse/signing.key"
chmod 644 "$SERVER_DIR/synapse/homeserver.yaml"
chmod 644 "$SERVER_DIR/synapse/log.config"

# Fix synapse_data volume permissions
docker run --rm -v server_synapse_data:/data alpine chown -R 991:991 /data 2>/dev/null || true

# =============================================================================
# Step 8: Build NexaLink UI
# =============================================================================
log "Building NexaLink UI..."
REPO_DIR="$(cd "$SERVER_DIR/.." && pwd)"

# Install Node.js if not available
if ! command -v node &>/dev/null; then
    log "Installing Node.js..."
    curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
    apt-get install -y -qq nodejs
fi

cd "$REPO_DIR"
npm install --production=false 2>/dev/null || npm install
npm run build

# Copy built files to nginx serving directory
mkdir -p "$SERVER_DIR/nginx/www/nexalink"
cp -r "$REPO_DIR/dist/"* "$SERVER_DIR/nginx/www/nexalink/"
log "NexaLink UI built and deployed."

# Write nexalink.conf for desktop app (contains server URL)
mkdir -p "$SERVER_DIR/nginx/www/nexalink/installers/desktop"
echo "$BASE_URL" > "$SERVER_DIR/nginx/www/installers/nexalink.conf"

# Step 8b: Build desktop installers (Windows EXE + Linux AppImage)
log "Building desktop installers..."
if [ -f "$REPO_DIR/scripts/build-installers.sh" ]; then
    chmod +x "$REPO_DIR/scripts/build-installers.sh"
    bash "$REPO_DIR/scripts/build-installers.sh" "$BASE_URL" 2>&1 || {
        warn "Desktop installer build failed (non-critical). You can build later with:"
        warn "  bash $REPO_DIR/scripts/build-installers.sh $BASE_URL"
    }
else
    warn "build-installers.sh not found, skipping desktop builds"
fi

# Step 8c: Build Android APK
log "Building Android APK..."
if [ -f "$REPO_DIR/scripts/build-android.sh" ]; then
    chmod +x "$REPO_DIR/scripts/build-android.sh"
    bash "$REPO_DIR/scripts/build-android.sh" "$BASE_URL" 2>&1 || {
        warn "Android APK build failed (non-critical). You can build later with:"
        warn "  sudo bash $REPO_DIR/scripts/build-android.sh $BASE_URL"
    }
else
    warn "build-android.sh not found, skipping Android build"
fi

# Step 8d: Build ALL native installers (Android Kotlin + Linux GTK4 + Windows)
log "Building native installers..."
if [ -f "$REPO_DIR/scripts/build-all-native.sh" ]; then
    chmod +x "$REPO_DIR/scripts/build-all-native.sh"
    bash "$REPO_DIR/scripts/build-all-native.sh" "$BASE_URL" 2>&1 || {
        warn "Native installer build failed (non-critical). Build later with:"
        warn "  sudo bash $REPO_DIR/scripts/build-all-native.sh $BASE_URL"
    }
else
    warn "build-all-native.sh not found"
fi

# =============================================================================
# Step 9: Start the stack
# =============================================================================
log "Starting NexaLink server stack..."
cd "$SERVER_DIR"

# Stop everything cleanly first
docker compose down 2>/dev/null || true

# Fresh install: remove ALL volumes to prevent DB conflicts
# (e.g. DuplicateTable errors when old postgres data meets new Synapse)
if [ ! -f "$SERVER_DIR/.installed" ]; then
    log "Fresh install — cleaning ALL old volumes..."
    docker compose down -v 2>/dev/null || true
    docker volume rm server_postgres_data server_synapse_data server_certbot_certs 2>/dev/null || true
fi

docker compose pull

# Start PostgreSQL first and wait for it
log "Starting PostgreSQL..."
docker compose up -d postgres

# Pre-create synapse_data volume and fix permissions BEFORE Synapse starts
log "Preparing Synapse data volume..."
docker volume create server_synapse_data 2>/dev/null || true
docker run --rm -v server_synapse_data:/data alpine sh -c "mkdir -p /data/media_store /data/uploads && chown -R 991:991 /data" 2>/dev/null || true
sleep 10

# Verify PostgreSQL is healthy
PG_HEALTHY=false
for i in $(seq 1 20); do
    if docker compose exec -T postgres pg_isready -U synapse 2>/dev/null; then
        PG_HEALTHY=true
        break
    fi
    sleep 2
done

if [ "$PG_HEALTHY" = "false" ]; then
    warn "PostgreSQL failed to start. Checking logs..."
    docker compose logs postgres --tail 10
fi

# Now start everything EXCEPT Synapse first
log "Starting infrastructure services..."
docker compose up -d postgres redis nginx element coturn synapse-admin admin-api prometheus grafana node-exporter

# Wait for postgres
sleep 5
PG_HEALTHY=false
for i in $(seq 1 30); do
    if docker compose exec -T postgres pg_isready -U synapse 2>/dev/null; then
        PG_HEALTHY=true
        break
    fi
    sleep 2
done
if [ "$PG_HEALTHY" = "false" ]; then
    warn "PostgreSQL slow to start — waiting more..."
    sleep 10
fi

# CRITICAL: Fix synapse_data volume permissions BEFORE starting Synapse
# This MUST happen after docker compose creates the volume but BEFORE Synapse runs
log "Fixing Synapse data permissions (CRITICAL)..."
docker volume create server_synapse_data 2>/dev/null || true
docker run --rm -v server_synapse_data:/data alpine sh -c "\
    mkdir -p /data/media_store /data/uploads /data/log && \
    chown -R 991:991 /data && \
    chmod -R 755 /data" 2>/dev/null || true

# NOW start Synapse with correct permissions
log "Starting Synapse..."
docker compose up -d synapse
sleep 5

log "Waiting for server to become healthy (this may take up to 4 minutes on first install)..."
RETRIES=120
HEALTHY=false
while [ $RETRIES -gt 0 ]; do
    if docker compose exec -T synapse python3 -c "import urllib.request; urllib.request.urlopen('http://localhost:8008/health')" 2>/dev/null; then
        HEALTHY=true
        break
    fi
    RETRIES=$((RETRIES - 1))
    sleep 3
done

# Ensure nginx and admin are running
docker compose up -d --no-deps nginx synapse-admin 2>/dev/null || true
sleep 5
# Verify synapse-admin is running
if docker compose ps synapse-admin 2>/dev/null | grep -q "Up"; then
    log "Synapse Admin panel is running."
else
    log "Restarting Synapse Admin..."
    docker compose restart synapse-admin 2>/dev/null || true
    sleep 5
fi

if [ "$HEALTHY" = "false" ]; then
    warn "Server is still starting up. It may need a few more seconds."
    warn "Check status with: cd $SERVER_DIR && docker compose ps"
fi

log "Server is running."

# Mark as installed (prevents volume wipe on re-run)
touch "$SERVER_DIR/.installed"

# =============================================================================
# Step 9b: Get Let's Encrypt certificate (trusted by all browsers)
# =============================================================================
log "Requesting Let's Encrypt certificate for $NIP_DOMAIN..."

# Install certbot if not available
if ! command -v certbot &>/dev/null; then
    apt-get install -y -qq certbot 2>/dev/null || true
fi

if command -v certbot &>/dev/null; then
    # Stop nginx briefly to use standalone mode (more reliable than webroot)
    docker compose stop nginx 2>/dev/null || true
    sleep 3

    # Open firewall ports if ufw is active
    if command -v ufw &>/dev/null; then
        ufw allow 80/tcp 2>/dev/null || true
        ufw allow 443/tcp 2>/dev/null || true
    fi

    # Try up to 3 times with different strategies
    SSL_OK=false

    # Attempt 1: standalone with nip.io
    log "SSL attempt 1: standalone mode..."
    certbot certonly --standalone \
        --non-interactive --agree-tos \
        --register-unsafely-without-email \
        -d "$NIP_DOMAIN" \
        --preferred-challenges http \
        2>&1 | tail -3 || true

    if [ -f "/etc/letsencrypt/live/${NIP_DOMAIN}/fullchain.pem" ]; then
        SSL_OK=true
    fi

    # Attempt 2: if failed, try with --break-my-certs (force)
    if [ "$SSL_OK" = "false" ]; then
        log "SSL attempt 2: force renewal..."
        certbot certonly --standalone \
            --non-interactive --agree-tos \
            --register-unsafely-without-email \
            -d "$NIP_DOMAIN" \
            --preferred-challenges http \
            --force-renewal \
            2>&1 | tail -3 || true

        if [ -f "/etc/letsencrypt/live/${NIP_DOMAIN}/fullchain.pem" ]; then
            SSL_OK=true
        fi
    fi

    if [ "$SSL_OK" = "true" ]; then
        # Copy Let's Encrypt certs to nginx ssl dir
        cp "/etc/letsencrypt/live/${NIP_DOMAIN}/fullchain.pem" "$SSL_DIR/nexalink.crt"
        cp "/etc/letsencrypt/live/${NIP_DOMAIN}/privkey.pem" "$SSL_DIR/nexalink.key"
        chmod 644 "$SSL_DIR/nexalink.crt"
        chmod 600 "$SSL_DIR/nexalink.key"
        log "Let's Encrypt certificate installed! No browser warnings."

        # Setup auto-renewal cron
        RENEW_CRON="0 4 * * * certbot renew --quiet && cp /etc/letsencrypt/live/${NIP_DOMAIN}/fullchain.pem ${SSL_DIR}/nexalink.crt && cp /etc/letsencrypt/live/${NIP_DOMAIN}/privkey.pem ${SSL_DIR}/nexalink.key && cd ${SERVER_DIR} && docker compose restart nginx >> /var/log/nexalink-certbot.log 2>&1"
        if ! crontab -l 2>/dev/null | grep -q "certbot renew"; then
            (crontab -l 2>/dev/null; echo "$RENEW_CRON") | crontab -
            log "Certificate auto-renewal cron installed."
        fi
    else
        warn "Let's Encrypt failed for $NIP_DOMAIN."
        warn ""
        warn "TO FIX THIS (choose one):"
        warn "  Option 1: Run fix-ssl script:"
        warn "    sudo $SERVER_DIR/scripts/fix-ssl.sh"
        warn ""
        warn "  Option 2: Use your own domain:"
        warn "    sudo $SERVER_DIR/scripts/fix-ssl.sh your-domain.com"
        warn ""
        warn "  Option 3: Open firewall ports and retry:"
        warn "    ufw allow 80/tcp && ufw allow 443/tcp"
        warn "    sudo $SERVER_DIR/scripts/fix-ssl.sh"
        warn ""
        warn "Using self-signed certificate for now."
        warn "Browsers will show warning -- click Advanced -> Proceed."

        # Generate a longer-lived self-signed cert (365 days)
        openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
            -keyout "$SSL_DIR/nexalink.key" \
            -out "$SSL_DIR/nexalink.crt" \
            -subj "/CN=${NIP_DOMAIN}/O=NexaLink/C=US" 2>/dev/null
        chmod 600 "$SSL_DIR/nexalink.key"
        chmod 644 "$SSL_DIR/nexalink.crt"
    fi

    # Restart nginx with new cert
    docker compose start nginx 2>/dev/null || docker compose up -d --no-deps nginx
else
    warn "certbot not available. Using self-signed certificate."
    warn "To fix: sudo apt install certbot && sudo $SERVER_DIR/scripts/fix-ssl.sh"
fi

# =============================================================================
# Step 9b: Enable firewall & DDoS protection
# =============================================================================
log "Setting up DDoS protection..."

# Apply iptables firewall rules
if [ -f "$SCRIPT_DIR/firewall.sh" ]; then
    chmod +x "$SCRIPT_DIR/firewall.sh"
    bash "$SCRIPT_DIR/firewall.sh" enable 2>/dev/null || warn "Firewall setup failed (non-critical)"
fi

# Install fail2ban
if [ -f "$SCRIPT_DIR/setup-fail2ban.sh" ]; then
    chmod +x "$SCRIPT_DIR/setup-fail2ban.sh"
    bash "$SCRIPT_DIR/setup-fail2ban.sh" 2>/dev/null || warn "fail2ban setup failed (non-critical)"
fi

chmod +x "$SCRIPT_DIR/ddos-monitor.sh" 2>/dev/null || true
log "DDoS protection enabled."

# Setup health monitoring cron
if [ -f "$SCRIPT_DIR/health-monitor.sh" ]; then
    chmod +x "$SCRIPT_DIR/health-monitor.sh"
    bash "$SCRIPT_DIR/health-monitor.sh" install 2>/dev/null || true
fi

# Setup log rotation
if [ -f "$SERVER_DIR/logrotate/nexalink" ]; then
    cp "$SERVER_DIR/logrotate/nexalink" /etc/logrotate.d/nexalink 2>/dev/null || true
    log "Log rotation configured."
fi

# Setup watchdog cron (every minute)
chmod +x "$SCRIPT_DIR/watchdog.sh" 2>/dev/null || true
WATCHDOG_CRON="* * * * * $SCRIPT_DIR/watchdog.sh"
if ! crontab -l 2>/dev/null | grep -q "watchdog.sh"; then
    (crontab -l 2>/dev/null; echo "$WATCHDOG_CRON") | crontab -
    log "Watchdog cron installed (every minute)."
else
    log "Watchdog cron already installed."
fi

# Setup SSL auto-renewal cron (weekly Monday 4am)
chmod +x "$SCRIPT_DIR/ssl-renew.sh" 2>/dev/null || true
SSL_CRON="0 4 * * 1 $SCRIPT_DIR/ssl-renew.sh"
if ! crontab -l 2>/dev/null | grep -q "ssl-renew.sh"; then
    (crontab -l 2>/dev/null; echo "$SSL_CRON") | crontab -
    log "SSL auto-renewal cron installed (weekly Monday 4am)."
else
    log "SSL renewal cron already installed."
fi

# Setup daily backup cron
BACKUP_CRON="0 */6 * * * $SCRIPT_DIR/backup.sh >> /var/log/nexalink-backup.log 2>&1"
if ! crontab -l 2>/dev/null | grep -q "backup.sh"; then
    (crontab -l 2>/dev/null; echo "$BACKUP_CRON") | crontab -
    log "Daily backup cron installed (3:00 AM)."
fi

# =============================================================================
# Step 9c: Verify external accessibility
# =============================================================================
log "Verifying server is accessible..."

# Check if port 80 is listening
if command -v ss &>/dev/null; then
    if ss -tlnp | grep -q ":80 "; then
        log "Port 80 is listening."
    else
        warn "Port 80 does NOT appear to be listening!"
        warn "Check: docker compose ps nginx"
    fi
fi

# Try to reach the server from localhost
if curl -sf --max-time 5 "http://127.0.0.1/health" >/dev/null 2>&1; then
    log "Server responds on localhost."
else
    warn "Server does not respond on localhost yet. It may still be starting."
fi

# Try to reach via the public IP
if curl -sf --max-time 10 "http://${SERVER_HOST}/health" >/dev/null 2>&1; then
    log "Server responds on ${SERVER_HOST} -- accessible from outside!"
else
    warn "Server does NOT respond on ${SERVER_HOST}."
    warn "Possible causes:"
    warn "  1. Firewall blocking port 80 (check: sudo ufw status / iptables -L)"
    warn "  2. Cloud provider security group not allowing port 80"
    warn "  3. Server is still starting up (wait 1-2 minutes)"
    warn "  4. Wrong IP address (detected: ${SERVER_HOST})"
fi

# =============================================================================
# Step 9: Create admin user (wait for Synapse to be fully ready)
# =============================================================================
log "Waiting for Synapse to be fully ready..."
SYNAPSE_READY=false
for i in $(seq 1 40); do
    if docker compose exec -T synapse python3 -c "import urllib.request; urllib.request.urlopen('http://localhost:8008/health')" 2>/dev/null; then
        SYNAPSE_READY=true
        break
    fi
    echo -n "."
    sleep 5
done
echo ""

if [ "$SYNAPSE_READY" = "true" ]; then
    log "Synapse is ready. Creating admin user: @${ADMIN_USER}:${SERVER_HOST}"
    docker compose exec -T synapse register_new_matrix_user \
        -u "$ADMIN_USER" \
        -p "$ADMIN_PASSWORD" \
        -a \
        -c /data/homeserver.yaml \
        http://localhost:8008 2>&1 || warn "Admin user may already exist (this is OK)"
    log "Admin user created."
else
    warn "Synapse did not become ready in time."
    warn "Create admin manually after Synapse starts:"
    warn "  cd $SERVER_DIR"
    warn "  source .env"
    warn "  docker compose exec synapse register_new_matrix_user -u \$ADMIN_USER -p \$ADMIN_PASSWORD -a -c /data/homeserver.yaml http://localhost:8008"
fi

# =============================================================================
# Step 10: Configure firewall for Docker compatibility
# =============================================================================
log "Configuring firewall..."

if command -v ufw &>/dev/null; then
    # Enable UFW if not active
    ufw --force enable 2>/dev/null || true

    # Add standard port rules
    ufw allow "$HTTP_PORT"/tcp comment "NexaLink HTTP" 2>/dev/null || true
    ufw allow 443/tcp comment "NexaLink HTTPS" 2>/dev/null || true
    ufw allow 3478/tcp comment "NexaLink TURN TCP" 2>/dev/null || true
    ufw allow 3478/udp comment "NexaLink TURN UDP" 2>/dev/null || true
    ufw allow 5349/tcp comment "NexaLink TURN TLS TCP" 2>/dev/null || true
    ufw allow 5349/udp comment "NexaLink TURN TLS UDP" 2>/dev/null || true
    ufw allow 49152:49172/udp comment "NexaLink TURN relay" 2>/dev/null || true

    # Fix Docker + UFW compatibility issue:
    # Docker bypasses UFW by adding iptables rules directly.
    # On systems with UFW policy DROP, external traffic to Docker ports is blocked.
    # This fix adds rules to the DOCKER-USER chain which UFW respects.
    UFW_AFTER="/etc/ufw/after.rules"
    if ! grep -q "NEXALINK-DOCKER-FIX" "$UFW_AFTER" 2>/dev/null; then
        log "Adding Docker+UFW compatibility rules..."
        cat >> "$UFW_AFTER" <<'DOCKERFIX'

# BEGIN NEXALINK-DOCKER-FIX
# Allow external access to Docker-published ports
*filter
:DOCKER-USER - [0:0]
-A DOCKER-USER -p tcp --dport 80 -j ACCEPT
-A DOCKER-USER -p tcp --dport 443 -j ACCEPT
-A DOCKER-USER -p tcp --dport 3478 -j ACCEPT
-A DOCKER-USER -p udp --dport 3478 -j ACCEPT
-A DOCKER-USER -p tcp --dport 5349 -j ACCEPT
-A DOCKER-USER -p udp --dport 5349 -j ACCEPT
-A DOCKER-USER -p udp --dport 49152:49172 -j ACCEPT
-A DOCKER-USER -j RETURN
COMMIT
# END NEXALINK-DOCKER-FIX
DOCKERFIX
        ufw reload
        log "Docker+UFW compatibility rules installed."
    else
        log "Docker+UFW compatibility rules already present."
    fi

    log "Firewall configured."
else
    # No UFW -- add iptables rules directly
    if command -v iptables &>/dev/null; then
        log "Adding iptables ACCEPT rules..."
        iptables -I INPUT -p tcp --dport "$HTTP_PORT" -j ACCEPT 2>/dev/null || true
        iptables -I INPUT -p tcp --dport 3478 -j ACCEPT 2>/dev/null || true
        iptables -I INPUT -p udp --dport 3478 -j ACCEPT 2>/dev/null || true
        iptables -I INPUT -p tcp --dport 5349 -j ACCEPT 2>/dev/null || true
        iptables -I INPUT -p udp --dport 5349 -j ACCEPT 2>/dev/null || true
        iptables -I INPUT -p udp --dport 49152:49172 -j ACCEPT 2>/dev/null || true
        log "iptables rules added."
    fi
fi

# =============================================================================
# Step 11: Setup relay cleanup cron job (every 6 hours)
#
# Relay model: messages are deleted from server after 1 day.
# Running every 6 hours ensures the server stays lean.
# =============================================================================
CLEANUP_SCRIPT="$SERVER_DIR/scripts/cleanup.sh"
chmod +x "$CLEANUP_SCRIPT"
CRON_LINE="0 */6 * * * $CLEANUP_SCRIPT >> /var/log/nexalink-cleanup.log 2>&1"
if ! crontab -l 2>/dev/null | grep -q "nexalink-cleanup\|nexalink/server/scripts/cleanup"; then
    (crontab -l 2>/dev/null; echo "$CRON_LINE") | crontab -
    log "Relay cleanup cron job installed (every 6 hours)."
else
    log "Cleanup cron job already exists."
fi

# =============================================================================
# Step 12: Setup daily database backup cron job
# =============================================================================
BACKUP_DIR="/var/backups/nexalink"
mkdir -p "$BACKUP_DIR"
BACKUP_CRON="0 2 * * * cd $SERVER_DIR && docker compose exec -T postgres pg_dump -U \${POSTGRES_USER:-synapse} \${POSTGRES_DB:-synapse} | gzip > $BACKUP_DIR/nexalink-db-\$(date +\\%Y\\%m\\%d).sql.gz && find $BACKUP_DIR -name 'nexalink-db-*.sql.gz' -mtime +7 -delete >> /var/log/nexalink-backup.log 2>&1"
if ! crontab -l 2>/dev/null | grep -q "nexalink-db-"; then
    (crontab -l 2>/dev/null; echo "$BACKUP_CRON") | crontab -
    log "Daily database backup cron job installed (2am, keeps 7 days)."
else
    log "Database backup cron job already exists."
fi

# Final nginx restart to pick up all installer files
cd "$SERVER_DIR"
docker compose restart nginx 2>/dev/null || true
sleep 3

# =============================================================================
# Done!
# =============================================================================
echo ""
echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}   NexaLink Server is running!${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""
echo -e "  Web client:    ${CYAN}${BASE_URL}${NC}"
echo -e "  Also via IP:   ${CYAN}https://${SERVER_HOST}${NC}"
echo -e "  Admin panel:   ${CYAN}${BASE_URL}/admin${NC}"
echo -e "  Config panel:  ${CYAN}${BASE_URL}/config${NC}"
echo -e "  Grafana:       ${CYAN}${BASE_URL}/grafana/${NC} (admin / nexalink123)"
echo -e "  Prometheus:    ${CYAN}${BASE_URL}/prometheus/${NC}"
echo -e "  Admin user:    ${CYAN}@${ADMIN_USER}:${SERVER_HOST}${NC}"
echo ""
echo -e "  Installers:"
echo -e "    Android:     ${CYAN}${BASE_URL}/installers/native/NexaLink-Android.apk${NC} (Native Kotlin)"
echo -e "    Windows:     ${CYAN}${BASE_URL}/installers/native/NexaLink-Windows.exe${NC} (Desktop)"
echo -e "    Linux:       ${CYAN}${BASE_URL}/installers/native/NexaLink-Linux${NC} (GTK4)"
echo -e "    Android Web: ${CYAN}${BASE_URL}/installers/NexaLink.apk${NC} (WebView)"
echo -e "    iOS:         ${CYAN}${BASE_URL}/installers/NexaLink-iOS.html${NC} (PWA)"
echo ""
echo -e "  Config file:   ${CYAN}${SERVER_DIR}/.env${NC}"
echo -e "  Logs:          ${CYAN}cd ${SERVER_DIR} && docker compose logs -f${NC}"
echo ""
echo -e "  ${YELLOW}IMPORTANT: Save your .env file securely. It contains all secrets.${NC}"
echo ""
